### ISSUE TITLE
GenerateNet

### ISSUE THREAD

**Issue by ghost** [thongphamthe/PAFit#1]
Hello.

When I use GenerateNet to form a Barabasi net, I export the edge list, and I try to measure the exponent of the degree distribution, it should be very close to 3, but it is quite far away for the generated net. 
 
Is this a problem in the PAFit package or am I generating the network badly?  

I attach an image where I compare the CDF for a Barabasi net built from Igraph (Blue line) and a Barabasi net built from PAFit (Red line).

![imagen](https://cloud.githubusercontent.com/assets/23464631/23222122/f46a7c26-f8f4-11e6-8e32-a0c6bc113b27.png)

Thank you!

Pd. The parameters are GenerateNet(N = 10000, m = 2, shape = 0, alpha = 1)

**Comment by thongphamthe** [comment]
Thanks for raising the issue. Could you provide the code of your experiment? That will help me greatly in debugging. You might want to use ```set.seed``` to remove randomness.
