### ISSUE TITLE
trouble with from_igraph()

### ISSUE THREAD

**Issue by ph-preux** [thongphamthe/PAFit#2]
Hi,
I'd generate a BA graph with: 
    net <- generate_BA (N = 1000)
Now, I want to consider the graph after each 100 growth iterations. I don't see how to do it in PAFit, so I use igraph and do: 
    g <- graph_from_edgelist (net$graph[1:100,1:2])

**Comment by ph-preux** [comment]
sorry, this was unfinished... I go on:
Then, 
    from_igraph (g)
[...]
Warning message:
In matrix(as.integer(as.matrix(as_data_frame(net))), ncol = 3) :
  la longueur des données [200] n'est pas un diviseur ni un multiple du nombre de lignes [67]
which (in French), means that the length of the target is not a multiple of the size of the source.

I don't understand this problem.
Moreover, this does not happen if I do:
  net2igraph <- to_igraph (net)
  igraph2net <- from_igraph (net2igraph)

So, I assume something goes wrong when I create the subnet, but why.

Thanks for your help (and many thanks for the PAFit package),
Ph.

**Comment by thongphamthe** [comment]
Hi,
The `to_igraph` and `from_igraph` functions of PAFit assume that the matrix has three columns, with the first two represent edges and the last shows time-stamps. 
In `to_igraph`, we use the function `graph.data.frame` of igraph to convert such a matrix.
So in your example, the following script works:
`g <- graph.data.frame (net$graph[1:100,1:3])`
Best,
